apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-viz.backendServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-viz.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    {{- include "k8s-viz.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
      protocol: TCP
